#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.digitalocean.com/ permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
