#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.digitalocean.com/ permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "/listen 80 default_server/a error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx restart
