#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.digitalocean.com/ permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal;}" etc/nginx/sites-available/default
sudo service nginx restart
